### ISSUE TITLE
gulp-rev-all@2 hash bug for css file in windows

### ISSUE THREAD

**Issue by elf-mouse** [smysnk/gulp-rev-all#209]
I find some hash bug for the resources of all css files  in windows.

**some css file**

```css
.logo {
  background: url(../images/logo.png);
}
```

when `gulp-rev-all@1.x`, revisioning:

```css
.logo {
  background: url(../images/logo.xxxxxxxx.png);
}
```

**but**, when `gulp-rev-all@2.x`, revisioning:

```css
.logo {
  background: url(../images/logo.png);
}
```

It's no hash for all `url`.
