### ISSUE TITLE
Bug in filepath Regex

### ISSUE THREAD

**Issue by claudioc** [smysnk/gulp-rev-all#42]
Hi,

just find out that if the CSS file contains a linear gradient definition, the regExp will also catch a lot of wrong references. Example:

``` css
       background: linear-gradient(to bottom, rgba(255,255,255,0) 15%,rgba(0,0,0,0.3) 100%);
```

will identify `top`,`255`,`to bottom`,`255` as references.

The same problem is with @media

``` css
    @media only screen and (min-width: $break-large) {
        background-color: $color-bg-default;
    }
```

will identify `min-width` as a reference.

I'd consider to use https://github.com/reworkcss/rework instead of a regular expression to catch file references.

Thank you for the hard work!
